name: EPO UX Patterns library

encoding: UTF-8

# Markdown parsing configuration
markdown: kramdown
kramdown:
auto_ids: true
parse_block_html: true

# All links in the design library will start with this baseurl
baseurl: "/epouxpatterns"

# The url for the home page of the design library
homeurl: "/epouxpatterns"

repository:
  name: simon-eastwood/epouxpatterns
  url: https://github.com/simon-eastwood/epouxpatterns

email: cbs@no-spam.org?subject=UX Patterns Library

# Set the default layout for everything in the docs folder to _layouts/pattern.html

defaults:
  - scope:
      path: "docs"
    values:
      layout: "pattern"


collections:
  - patterns
  output: true


  






