name: EPO UX Patterns library

encoding: UTF-8

# Markdown parsing configuration
markdown: kramdown
kramdown:
auto_ids: true
parse_block_html: true

# All links in the design library will start with this baseurl
baseurl: "/epouxpatterns"

# The url for the home page of the design library
homeurl: "/epouxpatterns"

repository:
  name: simon-eastwood/epouxpatterns
  url: https://github.com/simon-eastwood/epouxpatterns

email: cbs@epo.org?subject=UX Patterns Library

# Set the default layout for everything in the docs folder to _layouts/pattern.html
# this bit needs some auto generation. in the patterns content an "include_relative" is done, but unfortunately that only works with child directory.
# I wanted to then use a wildcard in this defaults list but jekyll doesnt support that (sigh). Not the dirs under patterns are hard coded here, but
# thats not how we want it. Solution would be to auto generate this defaults list in the build job
defaults:
  - scope:
      path: "docs"
    values:
      layout: "pattern"
  - scope:
      path: "docs/patterns/01-foundation/_preview-code"
    values:
      layout: "preview"
  - scope:
      path: "docs/patterns/02-atoms/_preview-code"
    values:
      layout: "preview"  
    - scope:
      path: "docs/patterns/03-molecules/_preview-code"
    values:
      layout: "preview"  
    - scope:
      path: "docs/patterns/04-organisms/_preview-code"
    values:
      layout: "preview"





